# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ SECRETS.DOCKER_USERNAME }}
        password: ${{ SECRETS.DOCKER_PASSWORD }}
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Push Docker Image to Docker Hub
      run: |
        docker tag ${{ SECRETS.DOCKER_USERNAME }}/backend-logistic:latest ${{ SECRETS.DOCKER_USERNAME }}/backend-logistic:${{ github.run_id }}
        docker push ${{ SECRETS.DOCKER_USERNAME }}/backend-logistic:${{ github.run_id }}
        docker push ${{ SECRETS.DOCKER_USERNAME }}/backend-logistic:latest
